name: MSBuild

on:
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      run: msbuild

  build-llvm:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build (llvm)
      run: msbuild /p:ClToolExe=clang-cl.exe /p:ClToolPath=$((gcm clang-cl).Path | Split-Path -Parent)
